package com.darkhorse.android.core.network.compiler

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.ParameterSpec
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.ksp.writeTo

internal class ApiServiceGenerator(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
) {

    fun generate(
        requestClassName: String,
        requestPackageName: String,
        requestTypeName: String,
        responseTypeName: String,
        url: String,
        method: String,
    ) {
        val apiInterfaceName = "${requestClassName}Api"
        val serviceClassName = "${requestClassName}Service"

        val requestType = ClassName.bestGuess(requestTypeName)
        val responseType = ClassName.bestGuess(responseTypeName)
        val targetPackage = requestPackageName

        val apiResultType = ClassName("com.darkhorse.android.core.network", "ApiResult")
            .parameterizedBy(responseType)

        val apiFactoryType = ClassName(
            "com.darkhorse.android.core.network",
            "ApiFactory",
        )

        val apiInterfaceType = ClassName(targetPackage, apiInterfaceName)

        val httpMethodAnnotation = AnnotationSpec.builder(
            ClassName("retrofit2.http", method),
        )
            .addMember("%S", url)
            .build()

        val apiInterface = TypeSpec.interfaceBuilder(apiInterfaceName)
            .addModifiers(KModifier.INTERNAL)
            .addFunction(
                FunSpec.builder("execute")
                    .addModifiers(KModifier.ABSTRACT, KModifier.SUSPEND)
                    .addAnnotation(httpMethodAnnotation)
                    .addParameter(
                        ParameterSpec.builder("body", requestType)
                            .addAnnotation(ClassName("retrofit2.http", "Body"))
                            .build(),
                    )
                    .returns(responseType)
                    .build(),
            )
            .build()

        val serviceClass = TypeSpec.classBuilder(serviceClassName)
            .addModifiers(KModifier.INTERNAL)
            .addAnnotation(ClassName("javax.inject", "Singleton"))
            .primaryConstructor(
                FunSpec.constructorBuilder()
                    .addAnnotation(ClassName("javax.inject", "Inject"))
                    .addParameter(
                        ParameterSpec.builder("apiFactory", apiFactoryType).build(),
                    )
                    .build(),
            )
            .addProperty(
                PropertySpec.builder("apiFactory", apiFactoryType)
                    .addModifiers(KModifier.PRIVATE)
                    .initializer("apiFactory")
                    .build(),
            )
            .addFunction(
                FunSpec.builder("execute")
                    .addModifiers(KModifier.SUSPEND)
                    .addParameter("request", requestType)
                    .returns(apiResultType)
                    .addCode(
                        buildString {
                            appendLine("val api = apiFactory.create<%API%>()")
                            appendLine("return try {")
                            appendLine("    %API_RESULT%.Success(api.execute(request))")
                            appendLine("} catch (e: java.lang.Exception) {")
                            appendLine("    %API_RESULT%.Exception(e)")
                            appendLine("}")
                        }
                            .replace("%API%", apiInterfaceName)
                            .replace("%API_RESULT%", "ApiResult"),
                    )
                    .build(),
            )
            .build()

        val fileSpec = FileSpec.builder(targetPackage, serviceClassName)
            .addFileComment(" Auto-generated by core-network-compiler. DO NOT EDIT.")
            .addType(apiInterface)
            .addType(serviceClass)
            .build()

        try {
            fileSpec.writeTo(
                codeGenerator = codeGenerator,
                dependencies = Dependencies(
                    aggregating = true,
                    *emptyArray(),
                ),
            )
            logger.info("Generated $serviceClassName for @ApiRequest($url, $method)")
        } catch (e: Exception) {
            logger.error("Failed to generate code for $requestClassName: ${e.message}")
        }
    }
}
